name: Build Android and IOS

on:
  push:
    branches:
      - master

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - user: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
