name: Deploy to Alpha
on:
  push:
    branches:
      - release/*
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install npm dependencies
        run: |
          npm install

      - name: Assemble Release Bundle
        run: |
          cd android && ./gradlew bundleRelease

      # - name: Sign Release
      #   uses: r0adkll/sign-android-release@v1
      #   with:
      #     releaseDirectory: android/app/build/outputs/bundle/release
      #     signingKeyBase64: ${{ secrets.SIGNING_KEY }}
      #     alias: ${{ secrets.ALIAS }}
      #     keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
      #     keyPassword: ${{ secrets.KEY_STORE_PASSWORD }}

      - name: Tag Release
        run: |
          version_name=${GITHUB_REF##*/}
          echo "Tagging release with tag $version_name"
          git tag $version_name release/$version_name
          git push origin --tags

      - name: Create service_account.json
        run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json

      - name: Deploy to Alpha
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: service_account.json
          packageName: com.githubactionsdemo
          releaseFile: android/app/build/outputs/bundle/release/app-release.aab
          track: alpha
          whatsNewDirectory: distribution/
